apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: blacklistclientip
  namespace: demonamespace
spec:
  responder-policies:
    - servicenames:
        - nscpx-cpx-service
      responder-policy:
        respondwith:
          http-payload-string: '"HTTP/1.1 403 Forbidden\r\n Server: nginx/1.8.1\r\nContent-Type: text/html\r\nConnection: close\r\n\r\n\r\n\r\n<h1>403 Forbidden. Access Denied by NetScaler BLX Ingress.\r\n\r\n\r\n</h1>"'
        respond-criteria: 'client.ip.src.TYPECAST_text_t.equals_any("blacklistips")'
        comment: 'Blacklist certain IP'


  patset:
    - name: blacklistips
      values:
        - '106.216.228.224'
        - '106.216.230.220'
        - '115.99.99.78'